apiVersion: apps/v1
kind: Deployment
metadata:
  name: newdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mbblab3
  template:
    metadata:
      labels:
        app: mbblab3
    spec:
      containers:
        - name: mbblab3
          image: azurembbregistry.azurecr.io/newspringapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: springboot-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: springboot-config
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: springboot-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASS

---
apiVersion: v1
kind: Service
metadata:
  name: mbblab-svc
spec:
  selector:
    app: mbblab3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 12001
  type: LoadBalancer
